flix/book

src/SUMMARY.md, src/effects.md
Adds chapter 10 on effects.
Should we perhaps change `h` to be defined as
```flix
pub def h(f: a -> b & ef1, g: b -> c & (not ef1 or ef2)): a -> c & (ef1 and ef2) =
x -> g(f(x))
```
give a complete example?
The section talks about the effects of `f` and `g` and what purity they're assigned at run-time but I think we could expand that a bit more with the implementation and perhaps a truth table?
```markdown
| ef1 | ef2 | not ef1 | not ef1 or ef2 | ef1 and ef2  |
| :-: | :-: | :-----: | :------------: | :----------: |
| t   | t   | f       | t              | t            |
| t   | f   | f       | f              | f            |
| f   | t   | t       | t              | f            |
| f   | f   | t       | t              | f            |
|     |     |         | purity of g    | puritfy of h …
```
=> feat: add chapter 10

.github/workflows/main.yml, book.toml
Fixes #15 
Just installs and runs `mdbook build` for now. The [Rust workflow](https://github.com/rust-lang/book/blob/main/.github/workflows/main.yml) is a bit more intensive and includes checking of spelling and tests the code. Presumably we could do something like this in the future.
=> feat: introduce CI workflow

src/tuples.md
Primed from the previous page's primitives examples that were nested ex. `Cons(1, Cons(2, Cons(3, Nil)))`, and the example on top that used a 2-tuple, I at first thought that the 4-tuple example was some form of syntactic sugar for a 2-tuple in a form either like `((a,b), (c,d))` or `(a, (b, (c, d)))`.
=> add comment of example's tuple degree

src/interoperability.md, src/introduction.md, src/records.md, src/references.md
Updates the syntax for record member type ascription. From `::` to `=` as per https://github.com/flix/flix/pull/4526
=> refactor: update record member type ascription syntax

src/data-types.md, src/enums.md, src/redundancy.md, src/type-aliases.md
Type parameter order changes to the docs where `Result` appears in quoted code. This matches changes to the stdlib where Result and Validation have had their type parameter orders changed so they can have instances for `Functor`, etc.
The `Validation` type does not appear in quoted code.
=> chore: Changes to type parameter order where Result is quoted in code

AUTHORS.md, src/concurrency.md, src/immutable-data.md, src/next-steps.md
A humble contribution, but a contribution none the less!
Additionally I was confused about the following things as I read through the book:
- The `!>` operator is used without introduction. I think a natural place to mention it would be under "Functions" > "Pipelines".
- I needed to run nightly to run many of the code examples. Maybe, while Flix hasn't reached a stable version yet it would be good to mention nightly in one of the first sections. Something like this would have helped me:
> Flix is actively being developed and haven't reached a stable version yet. Meanwhile we want to keep this book as in line with cutting edge Flix, so it is recommended that you use the [nightly build](https://flix.dev/nightly/) to make sure that you are able to run all examples.
=> chore: fix typos

src/primitive-types.md
This updates the desugared insertion ordering for sets and maps, and adds clarifications for both.
Fixes #91
=> fix: insertion ordering for maps and sets

src/parallelism.md
Related to https://github.com/flix/flix/issues/5874
=> chore: remove par-tuple from documentation

src/regions.md
Changed the word "Array" into "List", according to what was required by the context.
=> chore: fix a few typos

src/SUMMARY.md
As per title the [trait section](https://doc.flix.dev/taits.html) is currently empty since #110, see also image:
I considered also adding an automated check _"all files in summary actually exist"_ in the Github Action CI, but I'm not that skilled with bash scripting, sorry.
=> fix: typo in Summary preventing Trait section to be shown

src/precedence.md
=> chore: fix typo in `precedence.md`

src/concurrency.md
Had to make small adjustments to make examples compile.
Issue seems to be related to that change: flix/flix#5886
=> chore: fix typos in `concurrency.md`

src/identifiers.md
I'm not sure this covers all of the reserved identifiers, but these are the ones I have removed from the Flix library in preparation for the new parser.
=> feat: update reserved identifiers

src/pattern-matching.md
The section on records just extended the section on enums. This clearly separates the two.
=> feat: add sub section on record pattern matching

src/introduction.md
Fix compiler complaints in introductory examples for structured concurrency
e.g.
- before the change:
- after the change:
=> fix: add regions to channel examples

src/references.md
Now uses `Ref.fresh/get/put`
Related to https://github.com/flix/flix/pull/7371
=> docs: update reference syntax

src/foreach-yield.md, src/foreach.md
Some changes due to the feature associated types
=> chore: update signature due to Iterable and Collectable refactoring

src/common-problems.md, src/higher-kinded-types.md, src/introduction.md, src/records.md, src/references.md, src/type-level-programming.md
Searched through the repo with regex `([a-z]+)\w*\.[a-z]`
Related to https://github.com/flix/flix/issues/7897
=> docs: update `RecordSelect` syntax to `#`

src/next-steps.md
Changed "for" to "forM" to match newest valid flix syntax for monadic for-yield.
=> chore: update `next-steps.md`

src/concurrency.md
Removing the invalid Region parameter that is being passed to `Channel.timeout` in the concurrency example.
Reference: https://api.flix.dev/Channel.html
=> fix: correct concurrency example

src/getting-started.md
- Add a small section to the "Getting Started" guide on using Emacs
I have intentionally left out the details, instead pointing to the `flix-mode` package documentation. That way the getting started guide does not need to be updated if/when the setup of `flix-mode` for Emacs changes.
=> doc: add Emacs section to getting started guide

src/lattice-semantics.md
Each example in the lattice semantics examples just imports the constructors now. All other examples in the fixpoints chapter already compile as is.
Closes https://github.com/flix/book/issues/219
=> fix: ensure fixpoint chapter examples compile

src/effects-and-handlers.md
While reading this example (and the preceding example without lists) at first I wasn't sure what will happen when there is another element in the list. As one may expect, the execution halts after `0` is processed (so no result for division by 3 is printed out), but I think it may be beneficial to state this explicitly.
=> docs: show that exception stops execution in the divByZero example

src/build.md
This adds the information that `build-jar` and `build-fatjar` now automatically invoke the `build` command. 
See https://github.com/flix/flix/issues/11102 for more information.
=> feat: update `build` section with note about `build-jar`

src/getting-started.md
Instead of the detailed neovim setup I mentioned the official plugin, the version needed, and the background of what has changed slightly (one sentence about lspconfig and how it has changed in the most recent version of neovim).
=> refactor: replace detailed neovim setup with plugin
