flix/book

src/SUMMARY.md
src/lists.md

feat: add chapter 4

---

src/SUMMARY.md
src/references.md

feat: add chapter 6

---

src/SUMMARY.md
src/arrays.md

feat: add chapter 7

---

src/SUMMARY.md
src/namespaces.md

feat: add chapter 8

---

src/SUMMARY.md
src/concurrency.md

Adds chapter 9 on concurrency.

feat: add chapter 9

---

src/SUMMARY.md
src/fixpoints.md

feat: add chapter 11

---

src/SUMMARY.md
src/interoperability.md

Adds chapter 12 on interoperability.

feat: add chapter 12

---

src/SUMMARY.md
src/build-and-packages.md

Adds chapter 13 on build & packages

feat: add chapter 13

---

book.toml

feat: add GitHub links

---

src/arrays.md
src/concurrency.md
src/effect-casts.md
src/effects.md
src/fixpoints.md
src/functions.md
src/interoperability.md
src/introduction.md
src/lists.md
src/main.md
src/namespaces.md
src/printing-to-stdout.md
src/references.md
src/type-classes.md

Related to https://github.com/flix/flix/issues/4377

refactor: update to new effect syntax

---

theme/ayu-highlight.css
theme/highlight.css
theme/tomorrow-night.css

Related to https://github.com/flix/highlight.js/issues/7

feat: add substring highlighting

---

theme/highlight.js

This merges all the changes from https://github.com/flix/highlight.js/commit/ed0d9b8991fb5c87c103d38adbdb752a3da5581d into this repo.
In short this PR
- Adds more syntax highlighting
- Reduces the size of the highlight.js file to only a few hundred lines (down from 12k)

feat: add better syntax highlighting

---

src/SUMMARY.md
src/laziness.md

Followup to #56
Note, I've removed the delayed execution section as I struggled to come up with a suitably "real" example (without getting unnecessarily complicated), and I'm not sure it really adds much value.

A second attempt at documentation for lazy

---

src/SUMMARY.md
src/debugging.md

Fixes [#4698](https://github.com/flix/flix/issues/4698)

feat: Document new debug functions

---

src/debugging.md
src/effects.md
src/fixpoints.md
src/foreach-foryield.md
src/if-then-else.md
src/laziness.md
src/type-classes.md

fix: minor issues

---

theme/ayu-highlight.css
theme/highlight.css
theme/highlight.js
theme/tomorrow-night.css

Adds support for debug and fixes a few issues detailed in https://github.com/flix/highlight.js/issues/23

refactor: improve syntax highlighting

---

src/concurrency.md
src/introduction.md
src/parallelism.md

This addresses the "Update all documentation and website." task of https://github.com/flix/flix/issues/4850

chore: Update documentation to take account of regions in channels

---

src/references.md

feat: specify `ref e` sentence

---

src/references.md

Maybe this is just more confusing

feat: add note on the use of `Region` kind

---

src/arrays.md

feat: clarify polymorphism on primitive values

---

theme/highlight.js

Related to https://github.com/flix/highlightjs-flix/issues/37

feat: update theme with new keywords

---

src/companion-modules.md
src/essential-classes.md
src/fixpoints.md
src/higher-kinded-types.md
src/reading-and-writing-fields.md
src/regions.md

Fixed a few typos - LMK if any of these are intended!

chore: typos

---

src/foreach.md

chore: update foreach.md

---

theme/highlight.js

Fixes enum highlighting and corrects typo of `deafult` -> `default`. Also updates hightlight.js to latest version.

chore: update highlight.js

---

src/debugging.md
src/introduction.md
src/redundancy.md
src/references.md
src/unchecked-casts.md

Not much happening, just some typos that caught my eye while reading the book.

chore: fix some typos

---

src/next-steps.md

chore: fix typo in `next-steps.md`

---

src/creating-objects.md

feat: update `creating-objects.md`

---

src/next-steps.md

Noticed this when reading through the book. Similar to https://github.com/flix/book/pull/121.
FIXES #118

chore: fix typos in next-steps.md

---

src/type-ascriptions.md

Related to https://github.com/flix/flix/issues/7304

docs: update type ascription syntax

---

src/arrays.md
src/introduction.md
src/mutable-collections.md
src/regions.md

Related to https://github.com/flix/flix/issues/7329

chore: rename `Collection.new` to `Collection.empty`

---

src/calling-methods.md
src/creating-objects.md
src/exceptions.md
src/reading-and-writing-fields.md

Related to https://github.com/flix/flix/issues/7331

docs: update java import syntax

---

theme/highlight.js

Related to https://github.com/flix/highlightjs-flix/pull/43

feat: update highlight.js theme

---

theme/highlight.js

Closes https://github.com/flix/book/issues/144

fix: highlight trait keyword

---

src/getting-started.md

See #156. Nits are welcome.
Preview for convenience

feat: added nix as an installation option

---

src/automatic-derivation.md

fixes https://github.com/flix/flix/issues/7784

feat: add derivation of Coerce

---

src/companion-modules.md
src/identifiers.md
theme/highlight.js

Related to https://github.com/flix/flix/issues/8268

docs: add `redef` keyword

---

theme/highlight.js

Includes new keywords from https://github.com/flix/highlightjs-flix/issues/47

chore: update keywords

---

src/arrays.md
src/identifiers.md
src/introduction.md
src/mutable-collections.md
src/regions.md
src/structs.md

chore: reflect removal of `!` from certain mutating function names

---

src/primitive-types.md

Hey,
This adds a small section about regex literals as discussed in the https://github.com/flix/flix/issues/7741.
If there are any improvements or addition this section must include, feel free to ping me at anytime. 
PR is related to https://github.com/flix/flix/issues/7741.

feat: add section about regex literals

---

src/getting-started.md

A Neovim guide with minimal setup.

feat: add neovim guide

---

src/library-effects.md

Hey,
In addition to the PR [#9907](https://github.com/flix/flix/pull/9907), this PR updates the book to have the same function descriptions.
This relates also to https://github.com/flix/flix/issues/7034
Thank you :)

docs: update function description in library effects Random

---

theme/highlight.js

Updates highlightjs and includes `run` and `handler` keywords
https://github.com/flix/highlightjs-flix/pull/55
Related to https://github.com/flix/flix/issues/9638

chore: update highlightjs keywords

---

src/exceptions.md

Not true as of https://github.com/flix/flix/pull/10320

chore: remove nested try-catch restriction note

---

src/fixpoints.md
src/introduction.md
src/lattice-semantics.md

Related to https://github.com/flix/flix/issues/10756

feat: update to `inject ... into P/X`

---

src/foreach.md

https://github.com/flix/flix/issues/11016

feat: update foreach docs to reference ForEach trait instead of Iterable
